# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sarah Wang
tagline:          "hello :)"
description:       "Hi! I'm Sarah, a first-year at Yale University. Enjoy these snapshots of my life and thoughts!"
url:              http://swang392.github.io/
baseurl:          /

author:
  name:           "Sarah Wang"
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
